<?php

class UsersTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('users')->delete();
        
		\DB::table('users')->insert(array (
			0 => 
			array (
				'id' => 1,
				'username' => 'yogisalomo',
				'password' => '$2y$10$zIuFXG/LZRdTof4kJXk0E.s7Q2npRZviktr.s4NaI1aGdp26V8IIC',
				'picture' => 'yogi.jpg',
				'first_name' => 'Yogi',
				'last_name' => 'Sinaga',
				'birthdate' => '1993-08-02',
				'address_street' => 'Ligar Raya 41',
				'address_city' => 'Bandung',
				'address_province' => 'Jawa Barat',
				'address_country' => 'Indonesia',
				'role' => 'admin',
				'newsletter' => 1,
				'email' => 'yogi.salomo@gmail.com',
				'phone_number' => '08117304745',
				'registration_date' => '2012-01-01 00:00:00',
				'last_visit' => '2014-06-08 00:00:00',
				'is_premium' => 0,
				'premium_expired_date' => NULL,
				'status' => 'active',
				'remember_token' => NULL,
				'created_at' => '2014-09-22 03:30:25',
				'updated_at' => '2014-09-22 03:30:25',
				'escrow_amount' => NULL,
			),
			1 => 
			array (
				'id' => 2,
				'username' => 'haritselfahmi',
				'password' => '$2y$10$mNxbUMd891MZd8yPWSt/3ewgOuzz1haXs2KJHFAkGJoPiQAaREnOm',
				'picture' => 'sahe.jpg',
				'first_name' => 'Harits',
				'last_name' => 'Elfahmi',
				'birthdate' => '1992-04-21',
				'address_street' => 'Pejaten',
				'address_city' => 'Bandung',
				'address_province' => 'Jawa Barat',
				'address_country' => 'Indonesia',
				'role' => 'admin',
				'newsletter' => 1,
				'email' => 'adilelfahmi@gmail.com',
				'phone_number' => '08117304746',
				'registration_date' => '2012-01-02 00:00:00',
				'last_visit' => '2014-06-09 00:00:00',
				'is_premium' => 0,
				'premium_expired_date' => NULL,
				'status' => 'active',
				'remember_token' => NULL,
				'created_at' => '2014-09-22 03:30:25',
				'updated_at' => '2014-09-22 03:30:25',
				'escrow_amount' => NULL,
			),
			2 => 
			array (
				'id' => 3,
				'username' => 'sonnylazuardi',
				'password' => '$2y$10$Hn0Q83W3DjZOJckIgCMUXu58eddSgSO0eilJf8z6c.DKlJun4/7De',
				'picture' => 'sonny.jpg',
				'first_name' => 'Sonny',
				'last_name' => 'Lazuardi',
				'birthdate' => '1993-06-01',
				'address_street' => 'Sombalole Street',
				'address_city' => 'Johannesburg',
				'address_province' => 'Central South Africa',
				'address_country' => 'South Africa',
				'role' => 'admin',
				'newsletter' => 1,
				'email' => 'sonnylazuardi@gmail.com',
				'phone_number' => '08117304729',
				'registration_date' => '2012-01-03 00:00:00',
				'last_visit' => '2012-02-01 00:00:00',
				'is_premium' => 0,
				'premium_expired_date' => NULL,
				'status' => 'active',
				'remember_token' => NULL,
				'created_at' => '2014-09-22 03:30:25',
				'updated_at' => '2014-09-22 03:30:25',
				'escrow_amount' => NULL,
			),
			3 => 
			array (
				'id' => 4,
				'username' => 'fathanpranaya',
				'password' => '$2y$10$e2p19ejhkXSaaDyw3bnUjOkLEWKQEEAqIkzi3qiRJ51nz1eA5wX6S',
				'picture' => 'fathan.jpg',
				'first_name' => 'Fathan',
				'last_name' => 'Pranaya',
				'birthdate' => '1994-03-28',
				'address_street' => 'Villa Garuda Mas',
				'address_city' => 'Pekanbaru',
				'address_province' => 'Riau',
				'address_country' => 'Indonesia',
				'role' => 'admin',
				'newsletter' => 0,
				'email' => 'fathanpranaya@gmail.com',
				'phone_number' => '08117304727',
				'registration_date' => '2012-01-04 00:00:00',
				'last_visit' => '2014-05-08 00:00:00',
				'is_premium' => 0,
				'premium_expired_date' => NULL,
				'status' => 'active',
				'remember_token' => NULL,
				'created_at' => '2014-09-22 03:30:25',
				'updated_at' => '2014-09-22 03:30:25',
				'escrow_amount' => NULL,
			),
			4 => 
			array (
				'id' => 5,
				'username' => 'test',
				'password' => '$2y$10$U7v7eEJgPM79yeJ4WZnRo.NpDLTM4li0vM.Oume4QTT4OFKdFtKBS',
				'picture' => 'test.jpg',
				'first_name' => 'Test',
				'last_name' => 'Is',
				'birthdate' => '1993-08-02',
				'address_street' => 'Test',
				'address_city' => 'Test',
				'address_province' => 'Test Barat',
				'address_country' => 'Test',
				'role' => 'admin',
				'newsletter' => 1,
				'email' => 'test@suitcommerce.com',
				'phone_number' => '08117304245',
				'registration_date' => '2012-01-01 00:00:00',
				'last_visit' => '2014-09-22 10:31:28',
				'is_premium' => 0,
				'premium_expired_date' => NULL,
				'status' => 'active',
				'remember_token' => 'uFTZRM09exERHpyN0TDMUPvylcLFbAwrhR505wFyuGiGqNdUTngmZVSIYQCI',
				'created_at' => '2014-09-22 03:30:25',
				'updated_at' => '2014-09-22 03:31:28',
				'escrow_amount' => NULL,
			),
		));
	}

}
